import Image from "next/image";
import Link from "next/link";

function Chip(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <span className="rounded bg-blue-100 font-mono text-lg text-blue-800">
      {children}
    </span>
  );
}

export default function Home() {
  return (
    <>
      <h2> Next.js on Google Cloud Platform</h2>
      <div className="grid auto-cols-max grid-flow-col grid-cols-3 justify-items-center">
        <div className="w-10/12 rounded-xl bg-red-400 p-2 text-center font-mono">
          📈️ Scalable
        </div>
        <div className="w-10/12  rounded-xl bg-green-500 p-2 text-center font-mono">
          🕒 Available
        </div>
        <div className="w-10/12 rounded-xl bg-yellow-300 p-2 text-center font-mono">
          🤑 Affordable{" "}
        </div>
      </div>
      <p className="lead wg-10/12 rounded-xl bg-blue-500 p-4 text-center font-mono text-white">
        🔋 This Next.js app is powered by
        <br />
        serverless infrastructure on GCP 🔌
      </p>
      <p className="m-0 text-center font-mono">
        View the source on{" "}
        <a href="http://github.com" target="_blank" rel="noopener noreferrer">
          GitHub
        </a>
      </p>
      <div>
        <Image
          className="snap-center"
          src="/celebration.svg"
          alt="Celebrate"
          width={800}
          height={37}
          priority
        />
        <h3>Serverless Backend</h3>
        <p>
          Dynamic content is generated by server running on{" "}
          <a
            href="https://cloud.google.com/run/docs/overview/what-is-cloud-run"
            target="_blank"
            rel="noopener noreferrer"
          >
            Cloud Run
          </a>
          , a fully managed compute platform that automatically scales stateless
          containers. Visit{" "}
          <Link href="/ssr">
            <Chip>/ssr</Chip>
          </Link>{" "}
          page to see the server in action.
        </p>
        <h3>Global CDN</h3>
        <p>
          Static assets are served by{" "}
          <a
            href="https://firebase.google.com/docs/hosting"
            target="_blank"
            rel="noopener noreferrer"
          >
            Firebase Hosting
          </a>
          , a fast and secure way to host static content globally. Firebase
          Hosting also simplifies the process of connecting a custom domain for
          applications running on Cloud Run. Visit{" "}
          <Link href="/ssg">
            <Chip>/ssg</Chip>
          </Link>{" "}
          page to see a statically generated page served by Firebase Hosting.
        </p>
        <h3>Incremental Cache</h3>
        <p>
          Next.js cache handler is implemented with{" "}
          <a
            href="https://firebase.google.com/docs/database"
            target="_blank"
            rel="noopener noreferrer"
          >
            Firebase Realtime Database
          </a>
          , persisting cached pages and data to reduce server workloads by
          fulfilling requests from cached content when possible. Visit{" "}
          <Link href="/isr/time">
            <Chip>/isr/time</Chip>
          </Link>{" "}
          and{" "}
          <Link href="/isr/demand">
            <Chip>/isr/demand</Chip>
          </Link>{" "}
          pages to conditionally cached pages using incremental static
          regeneration.
        </p>
      </div>
    </>
  );
}
